### ISSUE TITLE
Rule: MA0016 Prefer return collection abstraction instead of implementation

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#12]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | MA0016 Prefer return collection abstraction instead of implementation |
| CheckId     | MA0016 |
| Category    | ? |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0016.md |

### What is the problem

```
List<T> or IList<T>
```

In a theoretical world, it sounds good to always use interfaces over concrete implementation. But this rule does not seem very good in practice and with reference to this post https://stackoverflow.com/questions/400135/listt-or-ilistt
with answers to the same questions by `Arec Barrwin`, I will suggest the general rule should be just use `List<T>` and if you want to over-engineering then feel free to use `IList<T>`.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.MS0016.severity = none

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0016.md

**Comment by perkops** [comment]
When returning from a extension method - e.g.:
```
        public static IEnumerable<Api.Generated.Contracts.Machines.Order> ToOrders(this IList<Entities.Order> orders)
        {
            if (orders == null)
            {
                throw new ArgumentNullException(nameof(orders));
            }

            return orders
                .Select(x => x.ToOrder())
                .ToList();
        }
```

And then utilizing this extension method from a handler - we get the following code:

```
        private async Task<GetOrdersByQueryResult> InvokeExecuteAsync(GetOrdersByQueryParameters parameters, CancellationToken cancellationToken)
        {
            var orderQueryOptions = parameters.ToOrderQueryOptions();
            var entities = await repository.GetOrdersByQueryAsync(orderQueryOptions, cancellationToken);
            return GetOrdersByQueryResult.Ok(entities.ToOrders().ToList());
        }
```

Do we really want this `entities.ToOrders().ToList()` ?

**Comment by egil** [comment]
As a general rule of thumb, I try to make my methods take as basic an abstraction as I can in input arguments, e.g. accepting `IEnumerable<string>` instead of `List<string>`, as that leaves the caller with the most options.

For output/return types, I like to avoid concrete implementations where possible, especially in public APIs in libraries, but do make them as feature rich as I can safely do (usually changeability in the future without breaking users). If I e.g. know that my collection will always be in memory, and have a known count, then `IReadOnlyCollection<string>` or `IReadOnlyList<string>` are good options, if the user has no reason to change the result. Otherwise `ICollection<string>` or `IList<string>` works well, but still allow me to add business logic later if needed, which returning a `List<string>` wont.

**Comment by egil** [comment]
For test projects, this should be `none` though.

**Comment by egil** [comment]
Microsoft has some details on this as well: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-parameters

**Comment by MrAndersPedersen** [comment]
Closed on normal projects but set to NONE on test projects.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0016.md
