### ISSUE TITLE
Rule: SA1611 Element Parameters Must Be Documented

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#27]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1611ElementParametersMustBeDocumented |
| CheckId     | SA1611 |
| Category    | Documentation Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1611.md |

### What is the problem

Sometimes the parameter makes enough sense based on the context they are used in, making a `<summary>` tag enough to document a public API. Forcing always to have parameter documentation added is a waste of time.

### Suggestion

Set it to `none` or `info`.

**Comment by davidkallesen** [comment]
@egil I just updated the table for you - Next time just replace `[Example: xxxx]` and not just replace the `xxxx`. For suggestion - also provide the target .editorconfig as root/src/test.

**Comment by davidkallesen** [comment]
I do not agree with your proposal. In my world, you fill in all the necessary documentation tags or do not use documentation tags at all as the SA1600 #5 that is disabled allows.

Often I see people using <summary> for comments and sometimes don't use <remarks> for that comment. Example, a link which should be in <remarks> instead of <summary> or even more correct, should just be specified with code comment as `/// Note: http://` or `/ * Note: http:// * /`.
@egil can you come with a example that require <summary> on a method and not <parameter> and don't belong to code-comment `///` or `/* */`

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
