### ISSUE TITLE
New analyzer: Meziantou

### ISSUE THREAD

**Issue by LarsSkovslund** [atc-net/atc-coding-rules#33]
We have never used this analyzer before, what are the reasons behind adding it?

**Comment by davidkallesen** [comment]
I don't see this as an issue but more like a question. Therefore I close it.
If you have a question or something to discuss, please use GitHub-Discussions instead.

But otherwise a short answer to your question: Yes, Meziantou makes some outstanding analyzer rules that usually provide good value. If you have any issues with these rules, take a trip past his [GitHub issues](https://github.com/meziantou/Meziantou.Analyzer/issues).
