### ISSUE TITLE
Rule: SA1122 UseStringEmptyForEmptyStrings

### ISSUE THREAD

**Issue by JKrag** [atc-net/atc-coding-rules#40]
### Rule summary

|                  | Value                                                            |
| ----------- |------------------------------------------------|
| Title          | [SA1122 UseStringEmptyForEmptyStrings]  |
| CheckId     | [SA1122]   |
| Category   | [Readability Rules] |
| Link        | https://documentation.help/StyleCop/SA1122.html |

### What is the problem

As a "Readability" rule, I would claim that exchanging `""` with `String.Empty` actually decreases readability in many places.
Once upon a time, in ancient .Net 1.x days, there were optimisation reasons for using String.Empty as `""` would instantiate a new String constant for every use, but to my knowledge this has long passed. 

Also, there are quite a few places in CSharp where String.Empty is actually not a legal replacement for `""` AFAIK. (like switch/case statements), so forcing people to learn this habit that can then not even be universally enforces seems plain wrong.

The only real downside of `""` that I can think of, is the off chance that it can hide zero-width characters, but a) who has ever had that happen in the wild? , and b) if this is a problem, there should probably be a rule specifically for this case, forcing devs to write a very explicit local rule override if they ever needed to out a `"<zero-width>xN"` string in the code on purpose.

### Suggestion

Suppress this rule in the standard ATC rule set.

**Comment by egil** [comment]
I almost assume the compiler is smart enough to simply replace all `""` with `string.Empty` at compile time. 
A quick test in [sharplab](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQLIAUAlBVTdwG4CGAJwIAPAgF4CAIkkBuLtQC+8gsu74ijABrtO2br0EEAnuKLoADADoAogFsADsCNy9NJdgVA=) seems to indicate different LI is generated by the compiler, but the JIT produced assembler code is indeed the same. So it might be that there is a very so slight overhead during runtime for the JIT to do it's work. 

That said, I do agree that this is not a readability concern, and more often than not I actually write "" in tests because it makes it easier to understand what is going on.

**Comment by perkops** [comment]
Pr. meeting 05/02-2020, we agreed upon that we want this rule enabled for src/props and set to none for test/props.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1122.md
