### ISSUE TITLE
Consider all StyleCop Documentation Rules

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#53]
Here is a link to all the relevant rules: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md

**Comment by JKrag** [comment]
@egil Can you expand a little bit on this issue, so that us outsiders can maybe contribute our opinions :-)

I am by the way all in favor of evaluating the use/severity of these documentation rules. I am not saying that they are necessarily "wrong", but just that they are probably so very far down on the "must fix" priority list for existing projects adding ATC rules, that they will probably stay on the custom exclude list indefinitely.  

Is this the point you are also hinting at?

**Comment by egil** [comment]
@JKrag I think my point was to just disable all these rules or at least set them as information, but we've decided to keep the current rules in place as is.
